; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_dig
	.word @sfx_ntsc_click

@sfx_ntsc_dig:
	.byte $8a,$0f,$89,$3f,$06,$00
@sfx_ntsc_click:
	.byte $84,$2c,$85,$00,$83,$3f,$89,$f0,$04,$00

.export sounds
