; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_title=music_data_title
.endif

music_data_title:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : title
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_title
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env3,@env0 ; 00 : Instrument 1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $71, $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $1f, $c5, $72, $24, $c5, $73, $1f, $c5, $74, $24, $c5
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $74, $1f, $c5, $24, $c5, $1f
@song0ref28:
	.byte $c5, $24, $c5, $48, $20, $c5, $24, $c5, $20, $c5, $24, $c5, $48, $22, $c5, $24, $c5, $22
	.byte $41, $0a
	.word @song0ref28
	.byte $c3, $00, $42
	.word @song0ch0loop
@song0ch1:
	.byte $ff, $ff, $9f
@song0ch1loop:
	.byte $80, $18, $78, $ff, $d5, $50, $b4, $24, $2b, $85, $1f, $bd, $50, $33, $2b, $26, $85, $1a, $ff, $cd, $50, $f4, $26, $27
	.byte $85, $1b, $bd, $50, $eb, $27, $29, $85, $1d, $ff, $cd, $50, $ed, $29, $2b, $85, $1f, $b5, $50, $13, $2b, $29, $85, $1d
	.byte $ff, $ff, $95, $50, $39, $29, $24, $85, $42
	.word @song0ch1loop
@song0ch2:
	.byte $ff, $ff, $9f
@song0ch2loop:
	.byte $80
@song0ref122:
	.byte $18, $95, $1d, $95, $1f, $95, $18, $95, $1d, $95, $1f, $95
	.byte $41, $0c
	.word @song0ref122
@song0ref137:
	.byte $14, $95, $1d, $95, $1f, $95, $14, $95, $1d, $95, $1f, $95
	.byte $41, $0c
	.word @song0ref137
@song0ref152:
	.byte $14, $95, $20, $95, $1f, $95, $14, $95, $20, $95, $23, $95
	.byte $41, $0c
	.word @song0ref152
	.byte $14, $95, $17, $95, $1a, $95, $1d, $95, $1f, $95, $20, $95, $26, $95, $20, $95, $1f, $95, $1d, $95, $1a, $95, $17, $95
	.byte $42
	.word @song0ch2loop
@song0ch3:
	.byte $ff, $ff, $9f
@song0ch3loop:
@song0ref198:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $42
	.word @song0ch3loop
@song0ch4:
	.byte $ff, $ff, $9f
@song0ch4loop:
	.byte $41, $0c
	.word @song0ref198
	.byte $42
	.word @song0ch4loop
