; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_title=music_data_title
.endif

music_data_title:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : title
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_title
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env3,@env0 ; 00 : Instrument 1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $ff, $48, $ff, $ff, $ff, $48, $ff, $ff, $ff, $48
	.byte $ff, $ff, $ff, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $75, $80
@song0ref26:
	.byte $27, $dd, $2e, $dd, $27, $dd, $2e, $dd, $29, $dd, $30, $dd, $29, $dd, $30, $dd
	.byte $41, $10
	.word @song0ref26
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80, $1d, $ff, $ff, $e5, $50, $0f, $29, $25, $95, $19, $ff, $ff, $e5, $50, $f1, $25, $29, $95, $1d, $ff, $ff, $e5, $50
	.byte $f9, $29, $2b, $95, $1f, $ff, $ff, $e5, $50, $07, $2b, $29, $95, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref90:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $0c
	.word @song0ref90
	.byte $42
	.word @song0ch4loop
